function B = bossData()
% bossData 5 张地图 Boss 原型（双阶段技能驱动）
% 运行期通过 scaleEnemy(boss,'boss',chapMul,roomMul,x,y) 缩放。

    B(1) = mkBoss('brawk','brawk','NRG','prodigy',1,1.00, ...
        [0.95 0.80 0.30], brawkP1(), brawkP2(), ...
        '冠军指挥型：控制+压制+召唤支援');
    B(2) = mkBoss('tenz','TenZ','SEN','peer',2,1.20, ...
        [0.95 0.35 0.55], tenzP1(), tenzP2(), ...
        '高机动明星：闪身换位+空中突袭');
    B(3) = mkBoss('aspas','aspas','LOUD','legend',3,1.44, ...
        [0.30 0.85 0.45], aspasP1(), aspasP2(), ...
        '顶级决斗：爆发点头+狂热爆发');
    B(4) = mkBoss('derke','Derke','FNC','peer',4,1.73, ...
        [1.00 0.55 0.35], derkeP1(), derkeP2(), ...
        '世界级双能进攻：位移爆发+终局斩杀');
    B(5) = mkBoss('forsaken','f0rsakeN','PRX','legend',5,2.07, ...
        [0.70 0.40 0.95], forsakenP1(), forsakenP2(), ...
        '终章混沌：次元穿梭+幻影分身');
end

% ---------------- constructors ----------------

function b = mkBoss(id,name,teamId,bossType,mapId,chapterMul,color,p1,p2,traits)
    b = struct( ...
        'id',id,'name',name,'displayName',name, ...
        'teamId',teamId,'bossType',bossType, ...
        'mapId',mapId,'chapterMul',chapterMul, ...
        'hpBase',900,'shieldBase',120,'dmgBase',28,'speedBase',2.7, ...
        'w',56,'h',72,'color',color, ...
        'phase1Skills',p1,'phase2Skills',p2, ...
        'phase2TriggerHpPct',0.50, ...
        'phase2StatMul',1.25, ...
        'phase2ShieldRegain',true, ...
        'lowHpCdBuffAt',0.40, ...
        'lowHpCdBuffMul',0.85, ...
        'traits',traits, ...
        'team','竞技联盟','region','-', ...
        'age',22,'honorTier',2, ...
        'kit',{{'阶段1','阶段2','冷却强化'}});
end

function s = mkSkill(id,name,kind,dmg,cd,rng,bspd,aoeR,effect)
    s = struct('id',id,'name',name,'kind',kind, ...
        'dmgBase',dmg,'cdBase',cd,'rangeBase',rng, ...
        'bulletSpdBase',bspd,'aoeR',aoeR,'effect',effect);
end

% ---------------- brawk (NRG) ----------------

function P = brawkP1()
    P = [ ...
        mkSkill('tacticalMark','战术标记','projectile',14,220,460,7,0,'reveal'), ...
        mkSkill('shockwave','震荡裂波','projectile',24,200,480,9,0,'stun'), ...
        mkSkill('rapidTap','连续点射','projectile_multi',16,180,460,8,0,'')];
end
function P = brawkP2()
    P = [ ...
        mkSkill('globalSuppress','全域压制','buff',0,260,0,0,0,'speedUp'), ...
        mkSkill('summonBots','支援召唤','summon',0,320,0,0,0,'summonBot'), ...
        mkSkill('champPulse','冠军脉冲','aoe',28,260,420,6,120,'shieldBreak')];
end

% ---------------- TenZ (Sentinels) ----------------

function P = tenzP1()
    P = [ ...
        mkSkill('flashStep','闪身突进','dash',24,180,300,0,0,''), ...
        mkSkill('headFive','五发爆头连射','projectile_multi',22,200,460,9,0,''), ...
        mkSkill('shadowDodge','影步规避','evade',0,220,0,0,0,'')];
end
function P = tenzP2()
    P = [ ...
        mkSkill('aerialStrike','空中突袭','dash',28,200,320,0,0,''), ...
        mkSkill('flashShift','全屏高速换位','dash',0,240,0,0,0,''), ...
        mkSkill('overdrive','极限爆发模式','buff',0,280,0,0,0,'speedUp')];
end

% ---------------- aspas (LOUD) ----------------

function P = aspasP1()
    P = [ ...
        mkSkill('lateralDash','高速横向位移','dash',22,180,280,0,0,''), ...
        mkSkill('headshotBurst','爆发点头连射','projectile_multi',24,200,460,9,0,''), ...
        mkSkill('obliqueCut','斜角切入突袭','dash',26,220,280,0,0,'')];
end
function P = aspasP2()
    P = [ ...
        mkSkill('airRush','空中冲刺射击','dash',26,180,300,0,0,''), ...
        mkSkill('bladeBurst','刀阵爆发','aoe',28,240,300,6,100,''), ...
        mkSkill('frenzyMode','狂热模式','buff',0,260,0,0,0,'speedUp')];
end

% ---------------- Derke (Fnatic) ----------------

function P = derkeP1()
    P = [ ...
        mkSkill('dashBurst','高速位移爆发','dash',24,180,280,0,0,''), ...
        mkSkill('airShot','空中射击','projectile',22,200,420,9,0,''), ...
        mkSkill('firePower','火力压场','projectile_multi',20,200,460,8,0,'')];
end
function P = derkeP2()
    P = [ ...
        mkSkill('faceRush','连续冲脸','dash',28,180,260,0,0,''), ...
        mkSkill('barrageWipe','弹幕扫荡','projectile_multi',24,240,480,9,0,''), ...
        mkSkill('executeMode','终局斩杀模式','buff',0,260,0,0,0,'execute')];
end

% ---------------- f0rsakeN (Paper Rex) ----------------

function P = forsakenP1()
    P = [ ...
        mkSkill('decoyBody','假身诱饵','summon',0,260,0,0,0,'summonBot'), ...
        mkSkill('ambushShift','突袭换位','dash',24,180,300,0,0,''), ...
        mkSkill('doubleFlash','双闪强攻','projectile_multi',26,200,460,9,0,'stun')];
end
function P = forsakenP2()
    P = [ ...
        mkSkill('dimShift','次元穿梭','dash',26,160,320,0,0,''), ...
        mkSkill('barrageBullet','连续弹幕','projectile_multi',28,200,480,10,0,''), ...
        mkSkill('phantomClone','幻影分身协战','summon',0,280,0,0,0,'summonBot')];
end
