function B = initBulletPool(maxBullets)
% initBulletPool 初始化固定容量子弹池

    if nargin < 1 || isempty(maxBullets)
        maxBullets = 260;
    end

    proto = struct( ...
        'active',false, ...
        'x',0,'y',0,'z',0, ...
        'vx',0,'vy',0,'vz',0, ...
        'owner','','life',0, ...
        'dmg',0,'color',[1 1 1],'crit',false, ...
        'pierce',false,'explode',false, ...
        'aoeR',0,'aoeDmgMul',0);
    B = repmat(proto, 1, maxBullets);
end

