function action = mainMenu(game)
% mainMenu 主菜单（左侧封面 + 右侧功能按钮）

    action = 'quit';
    hasSave = isfield(game,'saveFile') && isfile(game.saveFile);

    f = figure('Name','主菜单', ...
        'NumberTitle','off', ...
        'MenuBar','none', ...
        'ToolBar','none', ...
        'Resize','off', ...
        'Color',[0.08 0.10 0.14], ...
        'Position',[230 110 900 560], ...
        'CloseRequestFcn',@(~,~) choose('quit'));

    % 左侧封面
    coverPath = fullfile(fileparts(mfilename('fullpath')), '人物', 'ZMJJKK.png');
    axCover = axes('Parent',f, ...
        'Units','pixels', ...
        'Position',[34 96 390 430], ...
        'XTick',[],'YTick',[], ...
        'Color',[0.10 0.12 0.16], ...
        'Box','on');
    hold(axCover,'on');
    drawCover(axCover, coverPath);

    uicontrol(f,'Style','text', ...
        'String','枪神快跑：收藏与解锁版', ...
        'BackgroundColor',get(f,'Color'), ...
        'ForegroundColor',[1 0.92 0.5], ...
        'FontSize',18, ...
        'FontWeight','bold', ...
        'Position',[470 492 390 42]);

    y = 420;
    h = 46;
    gap = 12;
    w = 300;
    x = 520;

    mkBtn('开始游戏','start');
    y = y - (h+gap);

    cText = '继续游戏';
    if ~hasSave
        cText = '继续游戏（无存档）';
    end
    uicontrol(f,'Style','pushbutton','String',cText, ...
        'Position',[x y w h], ...
        'Enable', ternary(hasSave,'on','off'), ...
        'FontSize',12, ...
        'Callback',@(~,~) choose('continue'));
    y = y - (h+gap);

    mkBtn('选择关卡','select'); y = y - (h+gap);
    mkBtn('仓库 / 收藏','warehouse'); y = y - (h+gap);
    mkBtn('设置','settings'); y = y - (h+gap);
    mkBtn('退出游戏','quit');

    uicontrol(f,'Style','text', ...
        'String','提示：战斗内按 L 打开仓库，O/P 切换武器', ...
        'BackgroundColor',get(f,'Color'), ...
        'ForegroundColor',[0.75 0.82 0.95], ...
        'FontSize',11, ...
        'Position',[470 26 390 26]);

    uiwait(f);
    if isvalid(f)
        if isappdata(f,'menu_action')
            action = getappdata(f,'menu_action');
        end
        delete(f);
    end

    function mkBtn(label, act)
        uicontrol(f,'Style','pushbutton', ...
            'String',label, ...
            'Position',[x y w h], ...
            'FontSize',12, ...
            'Callback',@(~,~) choose(act));
    end

    function choose(act)
        if isvalid(f)
            setappdata(f,'menu_action',act);
            uiresume(f);
        end
    end
end

function drawCover(ax, coverPath)
    if isfile(coverPath)
        try
            img = imread(coverPath);
            image(ax, img);
            set(ax,'YDir','reverse');
            axis(ax,'image');
            axis(ax,'off');
            return;
        catch
        end
    end

    rectangle(ax,'Position',[0 0 1 1], ...
        'FaceColor',[0.13 0.15 0.20], ...
        'EdgeColor',[0.4 0.45 0.6], ...
        'LineWidth',1.2);
    text(ax,0.5,0.5,'封面加载失败', ...
        'HorizontalAlignment','center', ...
        'Color',[0.9 0.9 1], ...
        'FontSize',14, ...
        'FontWeight','bold');
    set(ax,'XLim',[0 1],'YLim',[0 1]);
end

function out = ternary(cond, a, b)
    if cond
        out = a;
    else
        out = b;
    end
end
