function data = weaponUnlockData()
% weaponUnlockData  12把武器解锁节奏与地图配置

    data.totalWeapons = 12;
    data.startingWeapons = 1; % 新档开局仅给一把，后续按地图解锁

    data.mapNames = { ...
        '隐世修所', ...
        '日落之城', ...
        '莲华古城', ...
        '源工重镇', ...
        '幽邃地窟'};

    data.mapUnlockWeapons = { ...
        [1 2 3], ...   % 地图1：基础武器
        [4 5 6], ...   % 地图2：中期强度
        [7 8 9], ...   % 地图3：高伤/功能
        [10 11 12], ...% 地图4：顶级基础枪械
        []};           % 地图5：不再解锁基础武器

    data.finalMapRewardHint = { ...
        '高品质皮肤', ...
        'Boss专属皮肤', ...
        '稀有强化奖励', ...
        '顶级收藏奖励'};
end
